local_manifests.xml: Switch to @sounddrill's kernel fork
fixes:

error: vendor/aosp/build/soong/Android.bp:58:1: module "qti_kernel_headers" already defined
       kernel/xiaomi/surya/Android.bp:30:1 <-- previous definition here